### ISSUE TITLE
Play button (on hover of artwork) doesn't appear when a track is already playing.

### ISSUE THREAD

**Issue by virjog** [awfy/pitch#10]
In other words, no way to change the track if one is already playing.

**Comment by virjog** [comment]
Appears to occur when switching tabs (from Latest to Popular or vice versa).

**Comment by awfy** [comment]
@virjog do you see the following error in your console:

`Uncaught TypeError: $.cachedScript is not a function`

**Comment by virjog** [comment]
@awfy Yep!

**Comment by awfy** [comment]
I think I have already fixed this on the development version. Will push it in the next hour or so to production.

**Comment by awfy** [comment]
@virjog the update is now live. You might need to press "Update extensions now" (with Developer mode enabled) on this page: chrome://extensions/

**Comment by virjog** [comment]
Problem still persists.

**Comment by awfy** [comment]
@virjog what is the version number you see on the extension list, should appear to the right of _Pitch for HypeMachine_.

**Comment by virjog** [comment]
@awfy 1.1.8

**Comment by awfy** [comment]
@virjog I can't seem to replicate this bug :(

**Comment by awfy** [comment]
@virjog do you still see the error I mentioned before in your console?

`Uncaught TypeError: $.cachedScript is not a function`

**Comment by virjog** [comment]
Cleared my cache and tried to replicate it but was unable to. Closing this for now, but if I experience it again, will let you know.

**Comment by awfy** [comment]
@virjog sweet! Thanks!
